#
# Copyright (C) 2021 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

include device/amlogic/g12-common/BoardConfigCommon.mk

DEVICE_PATH := device/hardkernel/odroidn2

## Bootloader
TARGET_BOOTLOADER_BOARD_NAME := odroidn2

## DTB
TARGET_DTB_NAME := meson64_odroidn2_android

## Kernel
BOARD_PREBUILT_DTBOIMAGE := 
TARGET_KERNEL_VARIANT_CONFIG := odroidn2_defconfig

## Partitions
# Sizes
BOARD_CACHEIMAGE_PARTITION_SIZE := 1073741824
BOARD_DTBOIMG_PARTITION_SIZE :=
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_SUPER_PARTITION_SIZE := 
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1879048192
BOARD_USERDATAIMAGE_PARTITION_SIZE := 576716800
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912

# TARGET_COPY_OUT_$PARTITION
TARGET_COPY_OUT_ODM := $(TARGET_COPY_OUT_VENDOR)/odm
TARGET_COPY_OUT_PRODUCT := $(TARGET_COPY_OUT_SYSTEM)/product

# Types
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := 
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := 
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := 
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true

## Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/init-files/fstab.amlogic

## Releasetools
TARGET_RELEASETOOLS_EXTENSIONS := $(DEVICE_PATH)/releasetools
